project:
  type: website

website:
  title: "blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  cookie-consent: true
  google-analytics: G-46H31NF5Y2

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    include-in-header: 
      - text: |
            <!-- Default Statcounter code for Invictus Quarto https://invictus.quarto.pub -->
            <script type="text/javascript">
            var sc_project=13016686; 
            var sc_invisible=1; 
            var sc_security="1325b7f6"; 
            </script>
            <script type='text/plain' cookie-consent="tracking">
            src="https://www.statcounter.com/counter/counter.js"
            async></script>
            <noscript><div class="statcounter"><a title="Web Analytics
            Made Easy - Statcounter" href="https://statcounter.com/"
            target="_blank"><img class="statcounter"
            src="https://c.statcounter.com/13016686/0/1325b7f6/1/"
            alt="Web Analytics Made Easy - Statcounter"
            referrerPolicy="no-referrer-when-downgrade"></a></div></noscript>
            <!-- End of Statcounter Code -->
editor: visual

