---
title: Finding the common characteristics among Top 10,000 movies of all time
---

## Setup

### Library

```{r}
library(tidyverse)
library(naniar)
library(summarytools)
library(janitor)
library(DataExplorer)
library(scales)
```

### Options

```{r}
update_geom_defaults("bar", list(fill = 'grey', color = 'black'))
```


### Dataset

```{r}
df <- read_csv('top_10_000_movies.csv', na = '\\N')
```
## Clean Data

```{r}
df
```

### Check Missing Data

```{r}
df |> 
  vis_miss()
```
### Check Numeric Distribution

#### Overall

```{r}
df |> 
  plot_histogram(ncol = 1)
```
#### Average Rating

```{r}
df |> 
  ggplot(aes(averageRating)) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = seq(0,10,1))
```

#### Runtime Minutes

```{r}
df |> 
  ggplot(aes(runtimeMinutes)) +
  geom_histogram()
```

```{r}
df |> 
  ggplot(aes(runtimeMinutes)) +
  geom_histogram(binwidth = 50) +
  scale_x_continuous(breaks = seq(0, 600, 50))
```


```{r}
df |> 
  ggplot(aes(runtimeMinutes)) +
  geom_histogram() +
  ylim(0,20)
```
#### Num Votes

```{r}
df |> 
  pull(numVotes) |> 
  cut(breaks = seq(1, 3000000, 100000), dig.lab = 50, right = FALSE, include.lowest = TRUE) |> 
  tabyl() |> 
  as.tibble() |> 
  rename(range = 1) |> 
  mutate(percent = label_percent(accuracy=0.001)(percent)) |> 
  select(-valid_percent)
  # mutate(percent = label_percent(accuracy=0.01)(percent))
  # mutate(range = format(range, big.mark = ','))
```
```{r}
df |> 
  ggplot(aes(numVotes)) +
  geom_histogram() +
  ylim(c(0, 100)) +
  scale_x_continuous(labels = comma)
```

```{r}
df |> 
  ggplot(aes(startYear)) +
  geom_histogram()
```
#### Genre

```{r}
df <- df |> 
  mutate(genres = fct_rev(fct_infreq(genres)))
```


```{r}
df |> 
  count(genres) |> 
  arrange(desc(n)) |>
  slice_head(n = 10) |> 
  ggplot(aes(n, genres)) +
  geom_col()
```


```{r}
df_unnested_genre <- df |> 
  mutate(genres = str_split(genres, ',')) |> 
  unnest_longer(genres) |> 
  mutate(genres = fct_rev(fct_infreq(genres)))
```


```{r}
df_unnested_genre |> 
  count(genres) |> 
  arrange(desc(n)) |> 
  slice_head(n = 10) |> 
  ggplot(aes(genres, n)) +
  geom_col() +
  coord_flip()
```

